language: python
python:
  -"3.6.5"
# command to install dependencies
install:
  - pip install -r API/tests/requirements.txt
#command to run tests
script:
  -pytest API/tests/test_create_request.py
  -pytest API/tests/test_modify_request.py
  -pytest API/tests/test_pick_single_request.py
  -pytest API/tests/test_request.py


